image: docker:latest

services:
  - docker:dind

stages:
  - maven-build
  - maven-test
  - docker-build

maven-build:
  script:
    - 'docker run -v /builds/host-mc/Spring-CI-test:/root/app --name build-maven maven:3.5.0-jdk-8-alpine sh /root/app/maven-build.sh'
    - 'cp target/*.jar app.jar'
    - 'docker rm -f build-maven'
  artifacts:
    paths:
      - 'app.jar'
# mvn clean install -DskipTests


docker-build:
  stage: build-docker
  script:
    - 'docker build --pull -t $CI_REGISTRY_IMAGE .'
    - 'docker push $CI_REGISTRY_IMAGE'
  only:
    - master
