stages:
- build
- test

image: maven:3.6.0-jdk-11-slim

build:
  stage: build
  script:
  - mvn clean install -DskipTests
  only:
    - master

junit:
  stage: test
  script:
  - mvn clean verify
  artifacts:
    reports:
      junit:
      - target/surefire-reports/TEST-*.xml
  only:
    - development

