image: docker:latest

services:
  - docker:dind

stages:
  - maven-build
  - maven-test
  - docker-build

maven-build:
  stage: maven-build
  script:
    - 'mvn clean install'
  artifacts:
    paths:
      - 'app.jar'

maven-test:
  stage: maven-test
  script:
    - 'mvn test' #'mvn clean install -DskipTests'

docker-build:
  stage: docker-build
  script:
    - './mvnw clean package -DskipTests=true dockerfile:build '
  only:
    - master
