stages:
  - build
  - test

build:
  stage: build
  image: maven:latest
  script:
    - mvn

junit:
  stage: test
  script:
  - mvn verify
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml

  

  
  
  
