stages:
- build
- test

image: maven:3.6.0-jdk-11-slim

build:
  stage: build
  script:
  - mvn clean install -DskipTests

junit:
  stage: test
  script:
  - mvn clean test
  artifacts:
    reports:
      junit:
      - target/surefire-reports/TEST-*.xml
