stages:
- build
- test

build:
  stage: build
  image: maven:3.6.0-jdk-11-slim
  script:
  - mvn

junit:
  stage: test
  image: maven:3.6.0-jdk-11-slim
  script:
  - mvn verify
  artifacts:
    reports:
      junit:
      - target/surefire-reports/TEST-*.xml